### ISSUE TITLE
refactor: unified API styles for the library

### ISSUE THREAD

**Issue by ericsyh** [streamnative/pulsar-admin-go#22]
### Background

The current library has different API styles for similar resources, e.g, to create a new tenant, namespace or topic:
* https://github.com/streamnative/pulsar-admin-go/blob/master/pkg/admin/tenant.go#L53
* https://github.com/streamnative/pulsar-admin-go/blob/master/pkg/admin/namespace.go#L334
* https://github.com/streamnative/pulsar-admin-go/blob/4862a8944e/pkg/admin/topic.go#L254

The API style is not consistent now and we need to update it to provide a unified style.

**Comment by maxsxu** [comment]
Close this in favor of tracking in https://github.com/apache/pulsar-client-go
