### ISSUE TITLE
[Bug] SinkConfig.InputSpecs param dont't work.

### ISSUE THREAD

**Issue by shibd** [streamnative/pulsar-admin-go#24]
Although the `InputSpecs` parameter is included in the configuration, but pulsar-admin-go does not handle it.

https://github.com/streamnative/pulsar-admin-go/blob/b31ddd22d16b9ebd4a313381d8ed8155a0ba91cb/pkg/utils/sink_config.go#L43

**Comment by maxsxu** [comment]
Close this in favor of tracking in https://github.com/apache/pulsar-client-go
