### ISSUE TITLE
CreateFunc returns 400 Bad Request

### ISSUE THREAD

**Issue by longtengz** [streamnative/pulsar-admin-go#27]
## Description

I tried to use `CreateFunc` to register a go pulsar function into a pulsar running in `standalone` mode, but got `400 Bad Request` error with the following code

```
funcConf := utils.FunctionConfig{
    Tenant:               "public",
    Namespace:            "default",
    Name:                 "gofunc",
    Runtime:              "GO",
    AutoAck:              true,
    Inputs:               []string{"test"},
    CleanupSubscription:  true,
    ProcessingGuarantees: "ATLEAST_ONCE",
    RetainOrdering:       true,
    Parallelism:          1,
}

// I can guarantee that the file is there, unless there's some permission stuff I don't know about this file should be able to open
AdminClient.Functions().CreateFunc(&funcConf, "/root/executable")
```

However, I successfully created one thru the following commands with almost identical options (as far as I can tell, I'm not sure what was actually being sent to pulsar tho)

```
bin/pulsar-admin functions create --go executable --tenant public --namespace default --inputs test --name gofunc --processingGuarantees ATLEAST_ONCE
```

I also tried starting pulsar with `PULSAR_LOG_LEVEL=debug`, but nothing interesting popped up

## Expectations

`CreateFunc` is supposed to return 200.

## How to reproduce

Just use the same config as I did in the above.

## Versions

pulsar `2.9.3`
pulsar-admin-go `v0.1.0`

**Comment by tisonkun** [comment]
Thanks for reporting this issue @longtengz!

Can you share the log or console output (stack trace) of "but got 400 Bad Request error with the following code"?

**Comment by longtengz** [comment]
@tisonkun The stack trace doesn't have anything useful for me to debug either

```
{
"level":"error",
"ts":1685953482.7875154,
"msg":"code: 400 reason: 400 Bad Request",
"stacktrace":"cmd/util/cmd.initPulsar\n\t/opt/web/cmd/util/cmd/init_pulsar.go:156
\ngyoza/cmd/util/cmd.glob..func8
\n\t/opt/web/cmd/util/cmd/init_pulsar.go:166
\ngithub.com/spf13/cobra.(*Command).execute\n\t/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860
\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
\ngithub.com/spf13/cobra.(*Command).Execute\n\t/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
\ngyoza/cmd/util/cmd.Execute\n\t/opt/web/cmd/util/cmd/root.go:31
\nmain.main\n\t/opt/web/cmd/util/main.go:6
\nruntime.main\n\t/usr/lib/go/src/runtime/proc.go:250"}
```

I tried pulsarctl cli, it worked as well.

```
pulsarctl functions create --go executable --tenant public --namespace default --inputs test --name gofunc --retain-ordering --p
arallelism 1 --processing-guarantees ATLEAST_ONCE --auto-ack -s http://127.0.0.1:8019 -v 4
```

**Comment by longtengz** [comment]
The only difference I can spot between the pulsar-admin-go options and those two cli ones are

`pulsar-admin-go`

```
RUNTIME: "GO"

// and then invoke CreateFunc with

CreateFunc(&funcConf, "executable")
```

`cli`

```
--go executable
```

**Comment by longtengz** [comment]
It turns out I was using the wrong api version for `functions`, should've used `v3` but used `v2`. 

Just add one more config when initializing admin client

```
PulsarAPIVersion: config.V3
```

**Comment by longtengz** [comment]
It turns out I was using the wrong api version for `functions`, should've used `v3` but used `v2`. 

Just add one more config when initializing admin client, then it'll return 200

```
PulsarAPIVersion: config.V3
```
