### ISSUE TITLE
Error improvements

### ISSUE THREAD

**Issue by flowchartsman** [streamnative/pulsar-admin-go#39]
Currently, in order to find out if something like a function/topic/subscription exists, you need to include the `rest` package and attempt a type assertion. This pretty much requires a helper to avoid tedious repetition and extra includes.

```go
import (
	pulsarrest "github.com/streamnative/pulsar-admin-go/pkg/rest"
)

// PulsarNotFound returns true if an error represents a missing Pulsar entity.
func PulsarNotFound(err error) bool {
	if err != nil {
		if re, ok := err.(pulsarrest.Error); ok {
			if re.Code == 404 {
				return true
			}
		}
	}
	return false
}
```

Given the common usecase of issuing a query to determine the existence of an object, a helper for this type should be provided at the very least, ideally in the root package.

Additionally, the use of a non-pointer type for `Error` means that the canonical Go usage of `errors.As` cannot work, since `errors.As` requires a pointer. Convention for custom error types is to use a pointer, and so pulsar-admin-go should probably adapt this as well.

Suggestions:

- `pulsar-admin-go/pkg/rest.Error` -> `pulsar-admin-go/*PulsarError`
- `pulsar-admin-go/func IsNotFound(err) bool`

This pattern enables similar patterns to those found in `os`, like [`os.IsPermission`](https://pkg.go.dev/os#IsPermission) and [`os.IsTimeout`](https://pkg.go.dev/os#IsTimeout)

**Comment by maxsxu** [comment]
Close this in favor of tracking in https://github.com/apache/pulsar-client-go
