### ISSUE TITLE
skipToLatest breaks function creation if < pulsar 3.0

### ISSUE THREAD

**Issue by flowchartsman** [streamnative/pulsar-admin-go#43]
[commit d28b89a11802d5bab694dae86bea56d6859e2fe3](https://github.com/streamnative/pulsar-admin-go/commit/d28b89a11802d5bab694dae86bea56d6859e2fe3) seems to have broken function creation, at least on Pulsar 2.10 and probably 2.11 too unless it was backported and I missed it.

Upon restoring [this line](https://github.com/streamnative/pulsar-admin-go/commit/d28b89a11802d5bab694dae86bea56d6859e2fe3#diff-d2d9eaf050c67d69494bb2f1f01e8b0260f14d9c73f1b186f432b3a86f250fa6L90) they started working again.

This is likely because `skipToLatest` is [new](https://github.com/apache/pulsar/pull/17214) and the validators for earlier versions will reject it, so even an explicit value of `false` will cause the submission to fail. It's really only lucky coincidence that `omitempty` allows it to work for <3.0, but without version checking there is almost no way for the user to know what went wrong, since the response from Jersey is laughably useless:

```
"servlet":"org.glassfish.jersey.servlet.ServletContainer-30a1b9b0", "message":"Bad Request"
```
If we plan on supporting <3.0, there should probably be some kind of layer in place to check for potential issues like this. I think we can probably get away with custom marshalling and warnings for things like this, allowing the user to continue to use the latest struct without breaking stuff, because `json.Marshal` isn't quite enough.

**Comment by maxsxu** [comment]
Close this in favor of tracking in https://github.com/apache/pulsar-client-go
